### PR TITLE
Six comes pre-installed with other packages, so remove it

### PR DESCRIPTION
**Pull request by Jbithell**
https://github.com/twilio/voice-quickstart-server-python/issues/9

### CODE REVIEW

**Comment by bchen-twilio** [comment]
@Jbithell 

Some of the users might have to deploy to environments without the `six` lib installed.
Could you clone the repository and remove the line in the `requirements.txt` and then deploy to Heroku?

Thanks

**Comment by Jbithell** [comment]
@bchen-twilio updated as requested

**Comment by idelgado** [comment]
@bchen-twilio what depends on six? And what requirement does this dep have on six? Could this be six>=1.0 or is it clear that only 1.x works in this case.

**Comment by bchen-twilio** [comment]
Python2 and Python3 need `six`.
`>=1.0` is equivalent to `==1.*` but I actually am not sure what exactly version of `six` is required. The latest version is `1.10.0` but the `1.4.0` works fine in my environment.

**Comment by bchen-twilio** [comment]
@Jbithell the change LGTM 👍 . Please squash the commits and merge the PR.
Thanks!

**Pull request merged**
